name: SSH PHP Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH key setup
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST_IP }} <<- 'ENDSSH'
            cd /var/www/html
            rm -rf ./*
            git clone https://github.com/wilsonneto-dev/SSH_Deployment_Example.git
            mv ./SSH_Deployment_Example/* ./
            export COMPOSER_ALLOW_SUPERUSER=1
            composer install
          ENDSSH
