name: Publishing React to Azure Blob Storage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH key setup
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Hello
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST_IP }} <<- 'ENDSSH'
            echo "hi" >> ./hi.txt
          ENDSSH
